name: Gradle Build
on:
  push:
    branches:
      - *
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew -s build
      - name: Publish Snapshot
        if: github.ref == 'refs/heads/master'
        env:
          ORG_GRADLE_PROJECT_octylNetUsername: ARMABOT-GitHub-Uploader
          ORG_GRADLE_PROJECT_octylNetPassword: ${{ secrets.ARMABOT_NEXUS_KEY }}
        run: ./gradlew -s publish
